apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring  # This selector must match the labels on your Pod
  ports:
    - protocol: TCP
      port: 8080    # Port on the Service
      targetPort: 8080  # Port on the Pod
  type:  NodePort 